######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : workflow3, Index = 0, Count = null
# SUBMIT FILE NAME : stage_out_local_local_1_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=6c1640a8-bf66-439f-bcf6-7f44edea7219 PEGASUS_WF_LABEL=workflow3 PEGASUS_DAG_JOB_ID=stage_out_local_local_1_0 PEGASUS_SITE=local _PEGASUS_TRANSFER_INPUT_FILES=/home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/00/00/count_ID0000003.meta,/home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/00/00/count_ID0000002.meta, PEGASUS_BIN_DIR=/home/scitech/pegasus/dist/pegasus-5.0.0dev/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "/home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart  -n pegasus::transfer -N null -i - -R local  -L workflow3 -T 2020-07-08T23:22:05+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-transfer  --threads 2 "
error = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002//00/00/stage_out_local_local_1_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-local.sh
input = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002//00/00/stage_out_local_local_1_0.in
log = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/workflow3-0.log
notification = NEVER
output = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002//00/00/stage_out_local_local_1_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 900
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "6c1640a8-bf66-439f-bcf6-7f44edea7219"
+pegasus_wf_uuid = "6c1640a8-bf66-439f-bcf6-7f44edea7219"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "workflow3-0"
+pegasus_wf_time = "20200708T232206+0000"
+pegasus_wf_xformation = "pegasus::transfer"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "stage_out_local_local_1_0"
+pegasus_job_class = 3
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
