######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : workflow3, Index = 0, Count = null
# SUBMIT FILE NAME : tar_ID0000004.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=6c1640a8-bf66-439f-bcf6-7f44edea7219 PEGASUS_WF_LABEL=workflow3 PEGASUS_DAG_JOB_ID=tar_ID0000004 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002//00/00/tar_ID0000004.err
executable = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/00/00/tar_ID0000004.sh
initialdir = /home/scitech/shared-data/wf-3/wf-scratch/LOCAL/scitech/pegasus/workflow3/run0002
log = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/workflow3-0.log
notification = NEVER
output = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002//00/00/tar_ID0000004.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 40
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = odd_count.txt,even_count.txt,/home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/00/00/count_ID0000003.meta,/home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/00/00/count_ID0000002.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0002/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = result.tar.gz
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "6c1640a8-bf66-439f-bcf6-7f44edea7219"
+pegasus_wf_uuid = "6c1640a8-bf66-439f-bcf6-7f44edea7219"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "workflow3-0"
+pegasus_wf_time = "20200708T232206+0000"
+pegasus_wf_xformation = "tar"
+pegasus_wf_dax_job_id = "ID0000004"
+pegasus_wf_dag_job_id = "tar_ID0000004"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
