######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : workflow3, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_2_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PEGASUS_HOME=/home/scitech/pegasus/dist/pegasus-5.0.0dev CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=1639bacb-8d09-4635-9399-d343cf7a0db7 PEGASUS_WF_LABEL=workflow3 PEGASUS_DAG_JOB_ID=register_local_2_0 PEGASUS_SITE=local"
arguments = " -n pegasus::rc-client -N null -R local  -L workflow3 -T 2020-07-08T23:14:54+00:00 /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0001/pegasus.4405515830697197297.properties -v --meta /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0001/00/00/tar_ID0000004.meta --insert /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0001/00/00/register_local_2_0.in"
error = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0001//00/00/register_local_2_0.err
executable = /home/scitech/pegasus/dist/pegasus-5.0.0dev/bin/pegasus-kickstart
log = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0001/workflow3-0.log
notification = NEVER
output = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0001//00/00/register_local_2_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 60
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "1639bacb-8d09-4635-9399-d343cf7a0db7"
+pegasus_wf_uuid = "1639bacb-8d09-4635-9399-d343cf7a0db7"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "workflow3-0"
+pegasus_wf_time = "20200708T231455+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_2_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
