######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : workflow3, Index = 0, Count = null
# SUBMIT FILE NAME : seperate_ID0000001.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=8da9dd6b-1c65-4d0e-b194-ff5db126957e PEGASUS_WF_LABEL=workflow3 PEGASUS_DAG_JOB_ID=seperate_ID0000001 PEGASUS_SITE=condorpool"
+WantIOProxy = True
error = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0003//00/00/seperate_ID0000001.err
executable = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0003/00/00/seperate_ID0000001.sh
initialdir = /home/scitech/shared-data/wf-3/wf-scratch/LOCAL/scitech/pegasus/workflow3/run0003
log = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0003/workflow3-0.log
notification = NEVER
output = /home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0003//00/00/seperate_ID0000001.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 1800)
priority = 20
should_transfer_files = YES
submit_event_user_notes = pool:condorpool
transfer_executable = true
transfer_input_files = nums4.txt,nums9.txt,nums3.txt,nums10.txt,nums1.txt,seperate,nums2.txt,nums8.txt,nums5.txt,nums6.txt,nums7.txt,/home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0003/00/00/stage_in_local_local_0_0.meta,/home/scitech/pegasus/dist/pegasus-5.0.0dev/share/pegasus/sh/pegasus-lite-common.sh,/home/scitech/shared-data/wf-3/scitech/pegasus/workflow3/run0003/pegasus-worker-5.0.0dev-x86_64_rhel_7.tar.gz
transfer_output_files = even_nums.txt,odd_nums.txt
universe = vanilla
when_to_transfer_output = ON_EXIT
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "8da9dd6b-1c65-4d0e-b194-ff5db126957e"
+pegasus_wf_uuid = "8da9dd6b-1c65-4d0e-b194-ff5db126957e"
+pegasus_version = "5.0.0dev"
+pegasus_wf_name = "workflow3-0"
+pegasus_wf_time = "20200708T234319+0000"
+pegasus_wf_xformation = "seperate"
+pegasus_wf_dax_job_id = "ID0000001"
+pegasus_wf_dag_job_id = "seperate_ID0000001"
+pegasus_job_class = 1
+pegasus_site = "condorpool"
+pegasus_job_runtime = 0
+pegasus_cores = 1
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
